= 07-学习c语言
:doctype: article
:encoding: utf-8
:lang: zh-cn
:toc: left
:toc-title: 导航目录
:toclevels: 2
:sectnums:
:sectanchors:

:hardbreaks:
:experimental:
:icons: font

[preface]
想要看懂hotspot源码,逃不过,理解和学习c语言;

推荐阅读::
https://wangdoc.com/clang/index.html[阮一峰的c语言教程]
非常感谢阮一峰老师的教程!学习c语言变得轻松很多!
但是作为初学者,我们还需要进一步总结下!

== 简介

=== 历史

C 语言最初是作为 Unix 系统的开发工具而发明的;
C 语言是在B语言的基础上开发的;
目前,Unix 和 Linux 系统现在还是使用 C 语言开发;

=== C语言的版本

- K＆R C
- ANSI C（又称 C89 或 C90）
- C95
- C99 目前最流行的版本
- C11
- C17
- C2x 据说可能会在2023年通过,到时就会称为C23;

=== C语言的编译

C 语言是一种编译型语言,源码都是文本文件,本身无法执行;必须通过编译器,生成二进制的可执行文件,才能执行;
使用C语言需要GCC编译器;如同运行java需要jdk方可运行;

> GCC在不同平台的安装

- MINGW在Windows平台下的安装
https://blog.csdn.net/wxh0000mm/article/details/100666329[]

- 在Ubuntu中安装
[source,bash]
----
# 更新包列表
sudo apt update

# 执行安装,此安装包含gcc,g++,make
sudo apt install build-essential
----

- 在Centos下安装
[source,bash]
----
# 更新包列表
sudo yum update

# 执行安装,此安装包含gcc,g++,make
sudo yum -y install gcc gcc-c++ kernel-devel
----

使用 `gcc -v` 来验证是否安装成功!

> GCC相关指令的熟练使用

安装gcc完成后,需要熟练使用gcc指令

gcc常用指令汇总::
https://wangchujiang.com/linux-command/c/gcc.html[linux-command]

当然你也可以使用 gcc --help来查看命令

常用命令一览
[source,bash]
----
gcc -c testfun.c    #将testfun.c编译成testfun.o

# 编译多个文件,test为输出文件
gcc testfun.c test.c -o test
# 替换成此命令
gcc *.c -o test
----

gcc命令 会在之后make文件中继续使用!

== 基本使用

说道C入门,就是要熟练使用printf方法

====
[source,c]
----
#include <stdio.h> <1>

int main(void) { <2>
  printf("Hello World\n");
  printf("%s will learn c language\n", "you");
  return 0;
}
----
<1> #include 表示为头文件,不引入头文件 printf 无法使用!
<2> main方法为 代码主入口;
====

挑战: 使用入门代码,编译通过并输出Hello World!

printf 最主要包含占位符,输出文本里面可以使用多个占位符;

常用的占位符,是和数据类型相关的;
如字符 char 对应占位符 为 %c;
如指针 point 对应占位符 为 %p;

先将常用的占位符列出,请关注数据类型小节;
- `%a`：浮点数;
- `%A`：浮点数;
- `%c`：字符;
- `%d`：十进制整数;
- `%e`：使用科学计数法的浮点数，指数部分的`e`为小写;
- `%E`：使用科学计数法的浮点数，指数部分的`E`为大写;
- `%i`：整数，基本等同于`%d`;
- `%f`：小数（包含`float`类型和`double`类型）;
- `%g`：6个有效数字的浮点数;整数部分一旦超过6位，就会自动转为科学计数法，指数部分的`e`为小写;
- `%G`：等同于`%g`，唯一的区别是指数部分的`E`为大写;
- `%hd`：十进制 short int 类型;
- `%ho`：八进制 short int 类型;
- `%hx`：十六进制 short int 类型;
- `%hu`：unsigned short int 类型;
- `%ld`：十进制 long int 类型;
- `%lo`：八进制 long int 类型;
- `%lx`：十六进制 long int 类型;
- `%lu`：unsigned long int 类型;
- `%lld`：十进制 long long int 类型;
- `%llo`：八进制 long long int 类型;
- `%llx`：十六进制 long long int 类型;
- `%llu`：unsigned long long int 类型;
- `%Le`：科学计数法表示的 long double 类型浮点数;
- `%Lf`：long double 类型浮点数;
- `%n`：已输出的字符串数量;该占位符本身不输出，只将值存储在指定变量之中;
- `%o`：八进制整数;
- `%p`：指针;
- `%s`：字符串;
- `%u`：无符号整数（unsigned int）;
- `%x`：十六进制整数;
- `%zd`：`size_t`类型;
- `%%`：输出一个百分号;

变量 运算符 流程控制 与java保持一致;无需记忆!

== 基本数据类型

=== 字符,整数和浮点数


- 字符类型
char 单字节;

字符类型在不同计算机的默认范围是不一样的;一些系统默认为-128到127，另一些系统默认为0到255;
这两种范围正好都能覆盖0到127的 ASCII 字符范围;

[source,c]
----
char x = 'B';
char x = 66;
char x = '\102'; // 'B'的八进制
char x = '\x42'; // 'B'的十六进制
----

- 整数int
位数不定

不同计算机的int类型的大小是不一样的;比较常见的是使用4个字节（32位）存储一个int类型的值，但是2个字节（16位）或8个字节（64位）也有可能使用;

- signed，unsigned

整数 int,默认 为 signed int;
但是 char,默认值,由系统决定,signed char 和 unsigned char都有可能!

- 整数的子类型

整数都是默认有符号的;

[source,c]
----
short int a;
long int b;
long long int c;

// int 可不写
// 你也可以写无符号的短整数
unsigned short a;
----

整数的极限值,忽略;

- 整数的进制

====
[source,c]
----
int x = 100;
printf("dec = %d\n", x); // 100
printf("octal = %o\n", x); // 144
printf("hex = %x\n", x); // 64
printf("octal = %#o\n", x); // 0144 <1>
printf("hex = %#x\n", x); // 0x64 <1>
printf("hex = %#X\n", x); // 0X64
----
<1> 注释即为整数的其他进制写法
====

- 浮点数
float 占用4字节
double 占用8字节
long double,占用16字节

[source,c]
----
float c = 10.5;
double x = 123.456e+3; // 123.456 x 10^3
// 等同于
double x = 123.456e3;
----

- 布尔类型

C 语言原来并没有为布尔值单独设置一个类型，而是使用整数0表示伪，所有非零值表示真;
C99 标准添加了类型_Bool，表示布尔值;但是，这个类型其实只是整数类型的别名，还是使用0表示伪，1表示真;
[source,c]
----
int x = 1;
if (x) {
  printf("x is true!\n");
}

_Bool isNormal;

isNormal = 1;
if (isNormal)
  printf("Everything is OK.\n");
----

=== 可移植性

在头文件 `stdint.h` 中引入了精确宽度类型

- `int8_t`：8位有符号整数;
- `int16_t`：16位有符号整数;
- `int32_t`：32位有符号整数;
- `int64_t`：64位有符号整数;
- `uint8_t`：8位无符号整数;
- `uint16_t`：16位无符号整数;
- `uint32_t`：32位无符号整数;
- `uint64_t`：64位无符号整数;

其中 `uint8_t`,即为单字节整数;在hotspot源码中大量存在;

=== sizeof

====
[source,c]
----
// 参数为数据类型
size_t x = sizeof(int); <1>

// 参数为变量
int i;
sizeof(i);

// 参数为数值
sizeof(3.14);
----
<1> sizeof 可以直接计算类型占用的字节数;
而sizeof返回值size_t,本质上是 unsigned int;
====

[[point]]
== 指针

熟练以下内容,即大致掌握了指针的用法!

指针一定要规范化名称,这样阅读代码才能更为迅速!

====
[source,c]
----
#include <stdio.h>
#include <stdint.h>

void intVariable(int intCopy);
void updateIntVariable(int *pInt);
void updateBroVariable(int *pInt);
void doublePoint(int *pInt);

int main() {

    printf("int size %d\n", sizeof(int));
    int paramInt = 1;
    printf("param address %p\n", &paramInt);
    intVariable(paramInt);

    return 0;
}

void intVariable(int intCopy) {
    int simpleInt = intCopy;
    printf("current variable init value %d\n", intCopy);

    printf("current variable address %p\n", &simpleInt);
    int *pInt = &simpleInt;
    updateIntVariable(pInt);
    printf("current variable value %d\n", simpleInt);

    updateBroVariable(pInt);
    doublePoint(pInt);
}

void updateIntVariable(int *pInt) {
    *pInt = *pInt + 1; <2>
    printf("current variable address %p\n", pInt);
}

void updateBroVariable(int *pInt) {
    int *pBroInt = pInt + 1; <3>
    *pBroInt = 3; <>
    printf("bro point address %p\n", pBroInt);
    printf("bro point real value %d\n", *pBroInt);
    printf("two point minus, result %d\n", pBroInt - pInt);
}

void doublePoint(int* pInt) {
    int **ppInt = &pInt; <4>
    int *pBroInt = pInt + 1;
    **ppInt = 4;
    *ppInt = pBroInt;

    printf("double point real value %d and address %p\n", **ppInt, *ppInt);
    printf("single point real value %d and address %p\n", *pInt, pInt);
}
----
<1> *号在变量声明处,代表声明了指针变量;
&simpleInt,代表取出simpleInt在内存中所在地址;
<2> *pInt = *pInt + 1; pInt原本是指针,而*号和指针变量在一起,此*号为运算符,意指从此地址取出实际存放的值;
<3> 2,3比较; int *pBroInt = pint + 1, 这里是对指针进行加法操作;即地址进行加法操作;得到当然是一个新的地址;
而此地址的值,是和sizeof(int)相关,请自行体会;
<4> int **ppInt = &pInt; &pInt此处是指pInt的地址;即指针的地址,&在此处为运算符;
====

熟练掌握 *号在当做指针声明 和 *,& 号当做运算符时的写法;

== 函数

=== 函数的声明和实现拆分

在学习指针时,我们已经使用了函数;但是我们基本上都会在多文件中使用函数;
我们改造下上面代码涉及的函数;将函数的声明和实现拆分,方便我们代码的复用;

- 头文件-函数的声明

.point_training.h
[source,c]
----
void intVariable(int intCopy);

void updateIntVariable(int *pInt);

void updateBroVariable(int *pInt);

void doublePoint(int *pInt);
----

- c文件-函数的实现

====
[source,c]
----
#include <stdio.h>
#include "point_tranning.h" <1>

// 函数的实现已经在指针的代码中说明,请自行copy
----
<1> 上面代码中，#include "point_training.h"表示加入头文件point_training.h;
这个文件没有放在尖括号里面，表示它是用户提供的;
它没有写路径，就表示与当前源码文件在同一个目录;
====

那我们的主文件只需要加入此头文件,就可以简化了;

=== 将函数本身当做指针处理

[source,c]
----
void functionHandler(void (*method)(int), int param);

void functionHandler(void (*method)(int), int param) {
method(param);
}
----

void (*method)(int) 意为着将入参为int,返回值为void的函数,当做参数;

比较特殊的是，C 语言还规定，函数名本身就是指向函数代码的指针，通过函数名就能获取函数地址;
[source,c]
----
(*method)(10);
(&method)(10);
method(10);

----
`(*method)(10)`, `(&method)(10)` 等同于 `method(10)`;

=== 可变参数

[sourec,c]
----
#include <stdarg.h>

double average(int i, ...) {
    double total = 0;
    va_list ap;
    va_start(ap, i);
    for (int j = 1; j <= i; ++j) {
        total += va_arg(ap, double);
    }
    va_end(ap);
    return total / i;
}
----

头文件`stdarg.h`定义了一些宏，可以操作可变参数;

- `va_list`：一个数据类型，用来定义一个可变参数对象;它必须在操作可变参数时，首先使用;
- `va_start`：一个函数，用来初始化可变参数对象;它接受两个参数，第一个参数是可变参数对象，第二个参数是原始函数里面，可变参数之前的那个参数，用来为可变参数定位;
- `va_arg`：一个函数，用来取出当前那个可变参数，每次调用后，内部指针就会指向下一个可变参数;它接受两个参数，第一个是可变参数对象，第二个是当前可变参数的类型;
- `va_end`：一个函数，用来清理可变参数对象;

== 数组

=== 数组的声明方式

[source,c]
----
    int arr[3];
    int arr1[3] = {1};
    int arr2[3] = {1, 2, 3};
    int arr3[3] = {[2]=1};
----

=== 数组不可再次声明的解释

注意,数组声明后,没法再次声明;
即 int arr[3]; 声明完成后;相当于所有成员声明值为0;
不能执行 arr = {1, 2, 3};
因为 此时的 arr(数组名) 指的是整个数组的指针;
即 arr(数组名) 是数组第一个元素地址;

我们将 arr当做指针变量; 则有表达式 `arr == &arr[0]`
arr(数组名称)只能当做指针变量来操作
`*arr = 10;` 即等价于 `arr[0] = 10;`
此处提现了 `variable = *(&variable)` 等式;

==== 数组的长度

====
[source,c]
----
    int scores[100];
    scores[100] = 51;<1>
    size_t arrLen = sizeof(scores) / sizeof(int);<2>
----
<1> scores[100] = 51,等价于 `*(scores+100)=51;`
强调的是 scores地址后的第100个地址的值为51;
但是此处便不会修改数组长度;数组长度只在声明时确定;对于变长数组也是成立的;

<2> 数组长度计算的表达式 `sizeof(arr)/ sizeof(arr_type);`
====

=== 二维数组与双指针变量

多维数组,我们只以二维数组来讨论;

[source,c]
----
int arr[3][3];
int arr1[3][3] = {
  {0, 1, 2},
  {3, 4, 5},
  {7, 8, 9}
};
int arr2[3][3] = {
  [1][1] = 1, [2][2] = 2
};
----

声明方式与一维数组保持一致;

但是二维数组与双指针变量,同样也保持了相同的关系;

如 `*arr[0] = &arr[0][0]`;

下面是一道挑战题目;辅助你更准确的理解指针与数组;
[source,c]
----
    int arr[3][3] = {
            {0, 1, 2},
            {3, 4, 5},
            {7, 8, 9}
    };

    **(arr + 1) = 100;
    *((*arr + 1)) = 200;
    *((*arr + 4)) = 300;

    for (int i = 0; i < 3; ++i) {
        for (int j = 0; j < 3; ++j) {
            printf("arr[%d,%d] address %p, value %d\n", i, j, &arr[i][j], arr[i][j]);
        }
    }
----

=== 数组的复制

数组的复制,可以将其视为指针,进行内存地址的复制;
详情查看 `内存管理` 小节

[source,c]
----
#include <string.h>

memcpy(dest, src, sizeof(dest));
----

== 字符串

C 语言没有单独的字符串类型，字符串被当作字符数组，即char类型的数组;

编译器会给数组分配一段连续内存，所有字符储存在相邻的内存单元之中;在字符串结尾，C 语言会自动添加一个全是二进制0的字节，写作\0字符，表示字符串结束;
[source,c]
----
{'H', 'e', 'l', 'l', 'o', '\0'}
// 等价于
"Hello"
----

当你在c中写了一个字符串,相当于写了一个以'\0'结尾的字符数组;

=== 字符串的声明

- 字符串声明解析

====
[source,c]
----
// 写法一
char s[6] = "Hello"; <1>
// 可简化为
char s[] = "Hello";

// 写法二
char *s = "Hello"; <2>
// 在写法2的基础上,此段操作会抛错;
s[0] = 'z';
----
<1> 注意声明长度为6,字符数组,最后一位为'\0'
通常 在声明字符数组时,字符数组的长度,可不写;由编译器根据字符串内容,去估算

<2> 使用指针声明字符串;此时s的内容并非是字符数组,而是一个地址,该地址指向了"Hello";
====

- 优雅的字符串声明

[source,c]
----
char greeting[50] = "Hello, how are you today!";

// 等同于,多个字符串合并,与shell脚本一致
char greeting[50] = "Hello, ""how are you ""today!";

// 等同于
char greeting[50] = "Hello, "
  "how are you "
  "today!";
----

=== 和字符串相关的函数

==== strlen()
strlen()函数返回字符串的字节长度，不包括末尾的空字符'\0';

====
[source,c]
----
#include <stdio.h>
#include <string.h>

char s[50] = "hello";
printf("%d\n", strlen(s));  // 5 <1>
printf("%d\n", sizeof(s));  // 50 <2>
----
<1> 字符串长度为5;
<2> 数组长度为50;
====

关于如何判断字符串长度,实际上是判断'\0'的位置;

==== strcpy() 和 strncpy()

字符串的复制，不能使用赋值运算符，直接将一个字符串赋值给字符数组变量;

[source,c]
----
char str1[10];
char str2[10];

str1 = "abc"; // 报错
str2 = str1;  // 报错
----

这里与 `数组的声明` 小节一致;无法再次声明数组;
因为数组的变量名是一个固定的地址，不能修改，使其指向另一个地址;
补充下: 当数组声明完成时,就已经分配了地址;

* strcpy()

如果我们想要复制字符串,可以使用 strcpy()函数;全量的复制另一个字符串;

[source,c]
----
strcpy(char dest[], const char source[]);
----
指定从source中全量的复制dest;

[source,c]
----
#include <stdio.h>
#include <string.h>

int main(void) {
  char s[] = "Hello, world!";
  char t[100];

  strcpy(t, s);

  t[0] = 'z';
  printf("%s\n", s);  // "Hello, world!"
  printf("%s\n", t);  // "zello, world!"
}
----

strcpy()函数有安全风险，因为它并不检查目标字符串的长度，是否足够容纳源字符串的副本，可能导致写入溢出;
如果不能保证不会发生溢出，建议使用strncpy()函数代替;

* strncpy()
指定从src中的最大位数n,复制dest;

[source,c]
----
char* strncpy(const char* dest, const char* src, size_t n);
----

[source,c]
----
char s1[40];
char s2[12] = "hello world";

strncpy(s1, s2, 5);
s1[5] = '\0';

printf("%s\n", s1); // hello
----

执行strncpy() 可以复制全部或部分字符串;

==== 其他字符串函数

- strcat() 和 strncat()
- strcmp() 和 strncmp()

暂时不用特别关注,当我们需要使用时,在研究;

=== 字符数组

[source,c]
----
char weekdays[][10] = {
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday"
};

char* weekdays[] = {
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday"
};
----

== struct结构

C 语言内置的数据类型，除了最基本的几种原始类型，只有数组属于复合类型，可以同时包含多个值，但是只能包含相同类型的数据，实际使用中并不够用;
struct 仍然是一种数据类型,它和java中的类有很大的区别;之后我们学习c++时,那时候才会有真正的class出现;

此小节,会避免介绍复杂的弹性数组成员;

=== struct声明

====
[source,c]
----
struct car {
  char* name;
  float price;
  int speed;
}; <1>

struct car saturn = {"Saturn SL/2", 16000.99, 175}; <2>

struct {
  char title[500];
  char author[100];
  float value;
} b1 = {"Harry Potter", "J. K. Rowling", 10.0},
  b2 = {"Cancer Ward", "Aleksandr Solzhenitsyn", 7.85}; <3>

typedef struct cell_phone {
  int cell_no;
  float minutes_of_charge;
} phone;
phone p = {5551234, 5}; <4>
----
<1> 声明 struct
<2> 声明 变量
<3> struct 和 变量同时声明; 按照java的习惯,不建议如此
<4> 使用typedef 替 cell_phone 简化; 仔细比较 <2>
====

=== 对齐空间

在声明结构体时,为了加快读写;
把内存占用划分成等长的区块，就可以快速在 Struct 结构体中定位到每个属性的起始地址;

[source,c]
----
struct foo {
  int a;        // 4
  char pad1[4]; // 填充4字节

  char *b;      // 8

  char c;       // 1
  char pad2[7]; // 填充7字节
};
printf("%d\n", sizeof(struct foo)); // 24
----

=== struct指针

====
[source,c]
----
#include <stdio.h>

struct turtle {
  char* name;
  char* species;
  int age;
};

void updateAge(struct turtle t) {
  t.age = t.age + 1; <1>
}
----
<1> 修改的是变量副本的属性
====

同 <<point>> 部分;在函数作用域中,参数实际上是入参的副本;
我们只有使用指针,才能实际修改,对应地址的值;

====
[source,c]
----
void udapteAge(struct turtle *t) {
    (*t).age = (*t).age + 1; <1>
}

udapteAge(&myTurtle);


void updateAgeSimple(struct *t) {
    t->age = t->age + 1; <2>
}

----
<1> 如此 修改属性太过麻烦;c中增加了 <2>的方式;
<2> t->age => 对指针操作的简化;
====

== typedef

typedef命令用来为某个类型起别名;

====
[source,c]
----
typedef char* String; <1>
String name;

typedef float app_float; <2>
app_float f1, f2, f3;
----
<1> 替char* 类型 起别名 String;之后则可直接使用;
<2> 方便以后为变量改类型, 如之后可以快速修改typedef long double app_float;
====

=== 简化方法的声明
这个目前还不能理解;特别是对复杂方法的简化;还没有遇到比较恰当的例子,先忽略;

== union 与 enum 数据结构

=== union
C 语言提供了 Union 结构，用来自定义可以灵活变更的数据结构;它内部可以包含各种属性，但同一时间只能有一个属性，因为所有属性都保存在同一个内存地址，后面写入的属性会覆盖前面的属性;这样做的最大好处是节省空间;

[source,c]
----
union quantity {
  short count;
  float weight;
  float volume;
};
----

=== enum
如果一种数据类型的取值只有少数几种可能，并且每种取值都有自己的含义，为了提高代码的可读性，可以将它们定义为 Enum 类型，中文名为枚举;

====
[source,c]
----
enum Letter {
  A,    // 0
  B,    // 1
  C = 4,  // 4
  D,    // 5
  E,    // 6
  F = 3   // 3
  G,    // 4
  H     // 5
} <1>

enum Letter letter; <2>
letter = A;
printf("%d", letter);

typedef enum Letter LetterEnum; <3>
----
<1> 枚举 会自动赋值 从0开始;枚举赋值只能为整数
<2> 枚举的使用举例,当然可以使用typedef对其简化
<3> 简化举例
====

== 预处理器

C 语言编译器在编译程序之前，会先使用预处理器（preprocessor）处理代码;
每个预处理指令都以#开头，放在一行的行首，指令前面可以有空白字符（比如空格或制表符）;#和指令的其余部分之间也可以有空格，但是为了兼容老的编译器，一般不留空格;

=== #define

====
[source,c]
----
#define MAX 100 <1>

----
<1> MAX 100就是我们定义的指令宏(macro)
====

> 宏是原样替换，指定什么内容，就一模一样替换成什么内容

关于原样替换,需要深入思考;

=== 带参数的宏

====
[source,c]
----
#define SQUARE(X) X*X <1>

// 替换成 z = 2*2;
z = SQUARE(2);

printf("%d\n", SQUARE(3 + 4)); <2>
----
<1> 这里的宏指令看起来类似于 函数;但和函数的区别就在于 原样替换
<2> SQUARE(3 + 4) = 3 + 4*3 + 4,可以看到和函数的本质区别
====

=== 运算符 # 和 ##

由于宏不涉及数据类型，所以替换以后可能为各种类型的值;如果希望替换后的值为字符串，可以在替换文本的参数前面加上#;

[source,c]
----
#define XNAME(n) "x"#n

// 输出 x4
printf("%s\n", XNAME(4));
----

如果替换后的文本里面，参数需要跟其他标识符连在一起，组成一个新的标识符，可以使用##运算符;它起到粘合作用，将参数“嵌入”一个标识符之中;
[source,c]
----
#define MK_ID(n) i##n

int MK_ID(1), MK_ID(2), MK_ID(3);
// 替换成
int i1, i2, i3;
----

== #undef

#undef指令用来取消已经使用#define定义的宏;

====
[source, c]
----
#define LIMIT 400
#undef LIMIT <1>

gcc -ULIMIT foo.c
----
<1> 取消定义LIMIT
<2> -U 指令,也是 取消宏定义
====

== #if...#endif

====
[source,c]
----
#define FOO 1

void method() {
    #if FOO <1>
      printf("defined\n");
    #else
      printf("not defined\n");
    #endif

    #if FOO == 1 <1>
        printf("foo value is 1");
    #elif FOO == 2
        printf("foo value is 2");
    #endif
}
----
<1> 通过0 和 1来判定
<2> 可以通过比较值得方式来判断
====

== #ifdef...#endif 和 #if defined

有时源码文件可能会重复加载某个库，为了避免这种情况，可以在库文件里使用#define定义一个空的宏;通过这个宏，判断库文件是否被加载了;

[source,c]
----
#ifdef FOO
#endif

#if defined FOO
#endif

#ifndef FOO
#endif

#if !defined FOO
#endif
----

=== 预定义宏
C 语言提供一些预定义的宏，可以直接使用;

- __DATE__：编译日期，格式为“Mmm dd yyyy”的字符串（比如 Nov 23 2021）;
- __TIME__：编译时间，格式为“hh:mm:ss”;
- __FILE__：当前文件名;
- __LINE__：当前行号;
- __func__：当前正在执行的函数名;该预定义宏必须在函数作用域使用;
- __STDC__：如果被设为1，表示当前编译器遵循 C 标准;
- __STDC_HOSTED__：如果被设为1，表示当前编译器可以提供完整的标准库；否则被设为0（嵌入式系统的标准库常常是不完整的）;
- __STDC_VERSION__：编译所使用的 C 语言版本，是一个格式为yyyymmL的长整数，C99 版本为“199901L”，C11 版本为“201112L”，C17 版本为“201710L”;

[source,c]
----
#include <stdio.h>

int main(void) {
  printf("This function: %s\n", __func__);
  printf("This file: %s\n", __FILE__);
  printf("This line: %d\n", __LINE__);
  printf("Compiled on: %s %s\n", __DATE__, __TIME__);
  printf("C Version: %ld\n", __STDC_VERSION__);
}
----

== 变量说明符

这里只说明常用的说明符;默认的不进行说明

- const
const说明符表示变量是只读的，不得被修改;

- static

** 用于局部变量（位于块作用域内部）;
static用于函数内部声明的局部变量时，表示该变量的值会在函数每次执行后得到保留，下次执行时不会进行初始化，就类似于一个只用于函数内部的全局变量;由于不必每次执行函数时，都对该变量进行初始化，这样可以提高函数的执行速度，详见《函数》一章
;
** 用于全局变量（位于块作用域外部）;
static用于函数外部声明的全局变量时，表示该变量只用于当前文件，其他源码文件不可以引用该变量，即该变量不会被链接（link）;
static修饰的变量，初始化时，值不能等于变量，必须是常量;

- register
register说明符向编译器表示，该变量是经常使用的，应该提供最快的读取速度，所以应该放进寄存器;但是，编译器可以忽略这个说明符，不一定按照这个指示行事;
设为register的变量，不能获取它的地址;

- volatile
如果``变量``被设定为volatile，编译器就不会把它放入缓存，每次都从原始位置去取``变量``的值，因为在两次读取之间，其他程序可能会改变``变量``;

- restrict
restrict说明符允许编译器优化某些代码;它只能用于指针，表明该指针是访问数据的唯一方式;

[source,c]
----
int* restrict pt = (int*) malloc(10 * sizeof(int));
----

== 关于I/O 和 文件处理
当我们需要时再去翻阅即可